services:
  backend:
    build: ./backend
    environment:
      PORT: 3000
      MONGO_URI: mongodb://admin:12345@mongo1:27017,mongo2:27017,mongo3:27017/pis?replicaSet=rs0&authSource=admin
    expose:
      - "3000"
    networks:
      - pis-net
  nginx:
    image: nginx:latest
    ports:
      - "8090:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - pis-net

networks:
  pis-net:
    external: true
