services:
  mongo:
    image: mongo:8.2
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: paolo
      MONGO_INITDB_ROOT_PASSWORD: paolo
    ports:
      - "27018:27017"
    volumes:
      - mongo_pfs_db_volume:/data/db
      - ./mongo_dump:/dump
      - ./mongo-restore.sh:/docker-entrypoint-initdb.d/mongo-restore.sh:ro

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://paolo:paolo@mongo:27017/demo?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo_pfs_db_volume:
